### ISSUE TITLE
Has the project support been abandoned?

### ISSUE THREAD

**Issue by valeriopisapia** [dougjohnston/angular-drum-machine#25]
@dougjohnston  I'd like to know if there are some updates regarding the Angular 2 version.

**Comment by dougjohnston** [comment]
@valeriopisapia Sorry, it's probably not going to happen. I had been hoping to upgrade this to Angular 2 (or higher), but haven't had the time. Feel free to fork this and give it a shot yourself though. I'll update the readme to be more accurate.
